[workspace.package]
authors = ["Talha Dar <muhammadtalhadar@gmail.com>"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/talhadaar/coding-challenges"

[workspace]
members = ["webserver", "webserver-bor"]
resolver = "2"

[workspace.dependencies]
tokio = "1.39.2"
