[workspace.package]
authors = ["Talha Dar <muhammadtalhadar@gmail.com>"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/talhadaar/coding-challenges"

[workspace]
members = ["webserver"]
resolver = "2"
