name: PR Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]
    types:
      - opened
      - synchronize
      - closed

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: "[CHECK] cargo fmt"
      run: cargo fmt --check
    - name: "[CHECK] cargo clippy"
      run: cargo clippy --release -- -Dwarnings
    - name: "[CHECK] cargo test"
      run: cargo test
