[package]
name = "webserver-bor"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
tokio = { workspace = true, features = ["full"] }